apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: ecomm-product
spec:
  selector:
    matchLabels:
      app: ecomm-product
  template:
    metadata:
      name: ecomm-product
      labels:
        app: ecomm-product
    spec:
      containers:
        - name: product-service
          image: vineettiwarigithub/ecomm-v2-productservice:latest
          ports:
            - containerPort: 8081
              name: product-port
  replicas: 1
          