# CI For Product Service
name: CI for Product Service

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/Checkout@v2
    
        - name: Set up Java
          uses: actions/setup-java@v2
          with:
            java-version: '21'
            distribution: 'temurin'
    
        - name: Build with Maven
          run: ./mvnw install -DskipTests

    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/Checkout@v2
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
                context: .
                file: Dockerfile
                push: true
                tags: vineettiwarigithub/ecomm-2-product-service:{{github.run_id}}
    